# Automatizare pentru a schimba răspunsurile random obișnuite cu unele mai nervoase atunci când se fac mai mult de 5 solicitări în 2 minute 
# Este necesar un contor numit ”counter.assist_random_wav_counter” cu limita maximă setată la 5

- id: '1697519248954'
  alias: Assist random wav
  description: ''
  trigger:
  - platform: state
    entity_id:
    - wake_word.porcupine
    - wake_word.openwakeword
    id: wakeword_detect
  - platform: template
    value_template: '{{ states(''counter.assist_random_wav_counter'')|float > 0 }}'
    id: wakeword_counter_reset >0
    enabled: true
    for:
      hours: 0
      minutes: 2
      seconds: 0
  - platform: template
    value_template: '{{ states(''counter.assist_random_wav_counter'')|float == 5 }}'
    id: wakeword_counter_reset = 5
    enabled: true
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - wakeword_detect
      sequence:
      - choose:
        - conditions:
          - condition: not
            conditions:
            - condition: template
              value_template: '{{ is_state(''counter.assist_random_wav_counter'',
                ''5'') }}'
          sequence:
          - service: shell_command.random_wav
            data: {}
          - service: counter.increment
            data: {}
            target:
              entity_id: counter.assist_random_wav_counter
        - conditions:
          - condition: template
            value_template: '{{ is_state(''counter.assist_random_wav_counter'', ''5'')
              }}'
          sequence:
          - service: shell_command.random_wav_nervous
            data: {}
    - conditions:
      - condition: trigger
        id:
        - wakeword_counter_reset >0
        - wakeword_counter_reset = 5
      sequence:
      - service: counter.reset
        data: {}
        target:
          entity_id: counter.assist_random_wav_counter
  mode: single

# Automatizare pentru butonul de status al boxei google home pentru satelit esp32 necesar pentru delay-ul cauzat de beeb-ul pe care îl face boxa google când pornește

  - id: '1705398527721'
  alias: Assist boxa google din birou status switch
  description: ''
  trigger:
  - platform: device
    device_id: 9b2ce56425da58cde14d1fbf3078e64d
    domain: media_player
    entity_id: 92d88bc4edb1e54a0985c58a0327da12
    type: turned_off
    id: boxa din birou off
  - platform: device
    device_id: 9b2ce56425da58cde14d1fbf3078e64d
    domain: media_player
    entity_id: 92d88bc4edb1e54a0985c58a0327da12
    type: idle
    id: boxa din birou on
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - boxa din birou off
      sequence:
      - type: turn_off
        device_id: 3023ad61f4a7b186fc537baca2d7a8fe
        entity_id: 36f98596c4869e74607765bc57577e04
        domain: switch
    - conditions:
      - condition: trigger
        id:
        - boxa din birou on
      sequence:
      - type: turn_on
        device_id: 3023ad61f4a7b186fc537baca2d7a8fe
        entity_id: 36f98596c4869e74607765bc57577e04
        domain: switch
  mode: single
